# TODO: re-enable Metric/AbcSize, Metrics/CyclomaticComplexity, and Metrics/PerceivedComplexity
AllCops:
  DisplayCopNames: true
  Exclude:
    - pkg/**/*
    - test/**/*
# Disabled useless assignment check due to Puppet type param validation
# e.g.
# validate do |value|
#   value = 'foo' if value == ''
# end
Lint/UselessAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/**/*_spec.rb"
Metrics/ClassLength:
  Max: 300
Metrics/LineLength:
  Max: 280
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/BlockDelimiters:
  Enabled: false
# enable Style/PredicateName as part of ruby_aem v2
Style/PredicateName:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
